env:
  - CMAKE_BUILD_TYPE=Release
  - CMAKE_BUILD_TYPE=Debug

os: linux
language: python
python: "3.7"
dist: bionic
compiler:
  - gcc
install:
  - pip install conan
  - conan user
script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  - cmake --build .
  - ctest -V .
