matrix:
  include:
    # Linux / GCC7 / Release  
    - os: linux
      dist: bionic
      compiler: gcc      
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" CMAKE_BUILD_TYPE=Release

    # Linux / GCC8 / Release  
    - os: linux
      dist: bionic
      compiler: gcc      
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" CMAKE_BUILD_TYPE=Release

    # Linux / GCC8 / Debug
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" CMAKE_BUILD_TYPE=Debug

    # macOS / Xcode10 / Release  
    - os: osx
      osx_image: xcode10
      compiler: clang      
      env:
        - MATRIX_EVAL="" CMAKE_BUILD_TYPE=Release

language: python
python: "3.7"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - pip install conan
  - conan user
script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  - cmake --build .
  - ctest -V .
