os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
  - pip install conan
  - conan user
script:
  - conan install .
  - cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ctest .
