image: Visual Studio 2017

platform:
  - x64

install:
  - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmmd: pip.exe install conan
  - cmmd: conan user
  - cmmd: conan --version

build_script:
  - cmmd: mkdir build
  - cmmd: cd build  
  - cmmd: conan install ..
  - cmmd: cmake ../  -G "Visual Studio 15 2017 Win64"
  - cmmd: cmake --build . --config Release --parallel 2
  - cmmd: ctest -V .
