image: Visual Studio 2017

platform:
  - x64

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user
  - conan --version

build_script:
  - mkdir build
  - cd build  
  - conan install ..
  - cmake ../  -G "Visual Studio 15 2017 Win64"
  - cmake --build . --config Release --parallel 2
  - ctest -V .
